name: Build PDF

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Build CSharp PDF
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: ./CSharp
          image_import: ./CSharp
          output_dir: pdfs
          theme: ./css/fluent.css
          highlight_theme: ./css/fluent.css
          build_html: false
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: PDF
          path: pdfs
